export { default as Home } from './Home/Home'
export { default as Discovery } from './Discovery/Discovery'
export { default as Explore } from './Explore/Explore'
export { default as Movie } from './Movie/Movie'
export { default as SignIn } from './SignIn/SignIn'
