export { default as Navbar } from './Navbar/Navbar'
export { default as Home } from './Home/Home'
export { default as BannerSection } from './BannerSection/BannerSection'
export { default as SectionSlider } from './SectionSlider/SectionSlider'
export { default as ListMovies } from './ListMovies/ListMovies'
